all:
  children:
    test:
      hosts:
        infra-test:
          ansible_host: 46.225.170.110
          ansible_user: root
    production:
      hosts:
        infra-prod:
          ansible_host: TBD
          ansible_user: root
